import Head from 'next/head'
// import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello Ostap!</h1>
        <section>
          <h2>Команда табору</h2>
          <ul>
            <li className="ostap">Остап</li>
            <li>Вітя</li>
            <li>Богдан</li>
            <li>Хаєцький</li>
          </ul>
        </section>
      </main>
    </>
  )
}
